all: factory publique

.PHONY: factory publique rapport clean

factory:
	cd factory; make

publique:
	cd publique; make

rapport:
	cd rapport; make

clean:
	cd factory; make clean
	cd publique; make clean
